import type { FeedGroup } from '~/types/feed'
import { getFavicon, getGhAvatar, getGhIcon, getQqAvatar, QqAvatarSize } from './utils/img'

export default [
	{
		name: '给予帮助の佬们',
		desc: '',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'Fomalhaut🥝',
				sitenick: '',
				title: '',
				desc: 'Future is now 🍭🍭🍭',
				link: 'https://fomal.cc/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://sourcebucket.s3.bitiful.net/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-10-16',
				comment: '我是看着这个大佬的视频搭建出第一个Hexo博客',
			},
			{
				author: '纸鹿本鹿',
				sitenick: '',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://www.zhilu.site/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-10-16',
				comment: '纸鹿佬！这个博客就是用的佬的模板',
			},
			{
				author: '安知鱼',
				sitenick: '',
				title: '',
				desc: '生活明朗 万物可爱',
				link: 'https://blog.anheyu.com/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '用Hexo的时候经常copy这个大佬的东西',
			},
			{
				author: 'Akilarの糖果屋',
				sitenick: '',
				title: '',
				desc: '期待您的光临！',
				link: 'https://akilar.top/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://npm.elemecdn.com/akilar-friends@latest/avatar/akilar.top.jpg',
				archs: ['Hexo', 'Netlify'],
				date: '2025-10-16',
				comment: '一位大佬，用过他的很多插件',
			},
			{
				author: 'Ariasaka',
				sitenick: '小窝',
				title: 'Ariasakaの小窝',
				desc: '人有悲欢离合 月有阴晴圆缺',
				link: 'https://blog.yaria.top/',
				feed: 'https://blog.yaria.top/feed',
				icon: 'https://blog.yaria.top/favicon.ico',
				avatar: getGhAvatar('LYXOfficial'),
				archs: ['Next.js', 'Vercel'],
				date: '2025-10-16',
				comment: '初中生，OIer，折腾博客。',
			},
			{
				author: 'MeuiCat',
				sitenick: '',
				title: '',
				desc: '足够优秀 再大方拥有.',
				link: 'https://meuicat.com/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://s11.ax1x.com/2023/07/07/pCc1TSO.jpg',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '借鉴过这位大佬的一些设计',
			},
			{
				author: '清羽飞扬',
				sitenick: '',
				title: '',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://blog.liushen.fun/info/avatar.ico',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '一个非常热心的佬佬，经常给我好多帮助🫰',
			},
		],
	},
	{
		name: '网上的朋友',
		desc: '一起互帮互助',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '微霞',
				sitenick: '',
				title: '',
				desc: '水风清，晚霞明',
				link: 'https://yuuu.org',
				feed: 'https://yuuu.org/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://cdn.yuuu.org/img/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-10-16',
				comment: '是学生（网站有点小卡，好像要挂魔法）',
			},
			{
				author: 'June\'s Blog',
				sitenick: '',
				title: '',
				desc: '遇事不决，可问春风',
				link: 'https://blog.june-pj.cn/',
				feed: 'https://blog.june-pj.cn/rss2.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://gitlab.com/June_PJ/PicGo-PJ/raw/main/img/avatar.webp',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-10-16',
				comment: '一个超厉害的后端大佬',
			},
			{
				author: '山岳库博',
				sitenick: '',
				title: '',
				desc: '开发学习启发性二刺螈',
				link: 'https://kmar.top/',
				feed: 'https://kmar.top/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://tuchuang.voooe.cn/images/2024/06/20/kmar.webp',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '一位很厉害的博主，Hexo的时候学了点东西',
			},
			{
				author: 'FloatSheep',
				sitenick: '',
				title: '',
				desc: 'On the other side of obstacles',
				link: 'https://blog.hesiy.cn',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://wsrv.nl/?url=github.com%2FFloatSheep.png%3Fsize=92',
				archs: ['Hugo', 'Cloudflare'],
				date: '2025-10-16',
				comment: '一只🐑，超厉害',
			},
			{
				author: 'HiPeach',
				sitenick: '',
				title: '',
				desc: '妙不可言',
				link: 'https://blog.opeach.cn',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://npm.elemecdn.com/opicture@1.0.0/main/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2025-10-16',
				comment: '学生，独立开发者',
			},
			{
				author: '呓语梦轩',
				sitenick: '',
				title: '',
				desc: '用心享受生活',
				link: 'https://blog.awaae001.top',
				feed: 'https://blog.awaae001.top/atom.xml',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://image.m-c.top/?/images/2024/01/13/Pqeh0v6VaK/ico.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2025-10-16',
				comment: '文艺复古风的网站',
			},
			{
				author: 'EastWind',
				sitenick: '',
				title: '',
				desc: '你好，我是东风',
				link: 'https://blog.1wind.cn/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://avatars.githubusercontent.com/u/125888129?v=4',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '东风，很厉害的后端大佬',
			},
			{
				author: '葱苓语畔',
				sitenick: '',
				title: '',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://blog.ciraos.top/api/f/RgeK/avatar1.avif',
				archs: ['Hexo', '服务器'],
				date: '2025-10-16',
				comment: '前端学习',
			},
			{
				author: 'Mikuの鬆',
				sitenick: '',
				title: 'Mikuの极光星',
				desc: '心有多宽，世界就有多远',
				link: 'https://blog.sotkg.com/',
				feed: '',
				icon: getFavicon('gug.thisis.host'),
				avatar: 'https://cravatar.cn/avatar/1012bf78fb01d5b964c3a9a0f515911a.png',
				archs: ['Nuxt', '服务器'],
				date: '2025-10-20',
				comment: '前端学习',
			},
		],
	},
] satisfies FeedGroup[]
